# the name of your JDBC driver
spending.datasource.driverClass: org.postgresql.Driver

# the username
spending.datasource.user: dev

# the password
spending.datasource.password: dev

# the JDBC URL
spending.datasource.url: jdbc:postgresql://127.0.0.1:5432/leaz

# any properties specific to your JDBC driver:
properties:
  charSet: UTF-8

# the maximum amount of time to wait on an empty pool before throwing an exception
spending.datasource.maxWaitForConnection: 1

# the SQL query to run when validating a connection's liveness
spending.datasource.validationQuery: "SELECT 1"

# the minimum number of connections to keep open
spending.datasource.spending.datasource.minSize: 1

# the maximum number of connections to keep open
spending.datasource.maxSize: 6

# whether or not idle connections should be validated
spending.datasource.checkConnectionWhileIdle: false

# how long a connection must be held before it can be validated
spending.datasource.checkConnectionHealthWhenIdleFor: 10

# the maximum lifetime of an idle connection
spending.datasource.closeConnectionIfIdleFor: 60